# Generated by Django 6.0.4 on 2026-04-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contactsubmission_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='category',
            field=models.CharField(choices=[('company-components', 'Company Components'), ('kirloskar', 'Kirloskar Projects'), ('machine', 'Machines')], max_length=50),
        ),
    ]
