# Generated by Django 6.0.3 on 2026-04-01 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ref_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('product', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('material', models.CharField(blank=True, max_length=100)),
                ('target_delivery', models.DateField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Quoted', 'Quoted'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='New', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='inquiries_status_281c6e_idx'), models.Index(fields=['company_name'], name='inquiries_company_66df72_idx')],
            },
        ),
        migrations.CreateModel(
            name='InquiryFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='inquiry_files/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='rfq.inquiry')),
            ],
            options={
                'db_table': 'inquiry_files',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, editable=False, max_digits=16)),
                ('delivery_time', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.CharField(choices=[('50% Advance, 50% on Dispatch', '50% Advance, 50% on Dispatch'), ('100% Advance', '100% Advance'), ('30 Days Credit', '30 Days Credit'), ('60 Days Credit', '60 Days Credit'), ('LC at Sight', 'LC at Sight')], default='50% Advance, 50% on Dispatch', max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='rfq.inquiry')),
            ],
            options={
                'db_table': 'quotations',
            },
        ),
    ]
